### ISSUE TITLE
'composeTransform' is not defined error

### ISSUE THREAD

**Issue by h4rm** [l0b0/paths2openscad#7]
Hey,

I'm getting the following error:

```
Traceback (most recent call last):
  File "paths2openscad.py", line 1004, in <module>
    e.affect()
  File "/Applications/Inkscape.app/Contents/Resources/extensions/inkex.py", line 221, in affect
    self.effect()
  File "paths2openscad.py", line 951, in effect
    self.document.getroot(), self.docTransform)
  File "paths2openscad.py", line 616, in recursivelyTraverseSvg
    self.recursivelyTraverseSvg(node, matNew, v)
  File "paths2openscad.py", line 616, in recursivelyTraverseSvg
    self.recursivelyTraverseSvg(node, matNew, v)
  File "paths2openscad.py", line 647, in recursivelyTraverseSvg
    matNew2 = composeTransform(
NameError: global name 'composeTransform' is not defined
```

with OSX Yosemite and Inkscape 0.48.5 r10040.
Any ideas what causes this?

**Comment by l0b0** [comment]
I'm afraid I'm no longer maintaining this repository.

**Comment by jnweiger** [comment]
Tested with inkscape 0.91 on linux. Works great so far. @l0b0 I'd suggest to upgrade to 0.91 if possible.
Also for many other reasons. Closing here. Please reopen, if this is still an issue.
