### ISSUE TITLE
Imported SVG, tried to Generate paths but failed

### ISSUE THREAD

**Issue by robtarr** [l0b0/paths2openscad#9]
Traceback (most recent call last):
  File "paths2openscad.py", line 1004, in <module>
    e.affect()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 265, in affect
    self.getposinlayer()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 207, in getposinlayer
    x = self.unittouu( xattr[0] + 'px' )
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 351, in unittouu
    return retval * (self.__uuconv[u.string[u.start():u.end()]] / self.__uuconv[self.getDocumentUnit()])
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 304, in getDocumentUnit
    p = param.match(svgwidth)
TypeError: expected string or buffer

**Comment by su-v** [comment]
This is a known upstream bug in Inkscape when applying a python-based script extension which uses the 'inkex.Effect' class in SVG files which do not define 'width' for the top-level <svg> element:
* Bug 1463623: [Error trying to save Optimized SVG (no 'width' attribute for SVGRoot)]
(https://bugs.launchpad.net/inkscape/+bug/1463623)

**Comment by jnweiger** [comment]
I cannot reproduce this with current inkscape-0.91 -- scad files are generated niceley for me. 
@robtarr is this still an issue for you? Otherwise I suggest to close here.
